### ISSUE TITLE
[Refactor] 코드리뷰

### ISSUE THREAD

**Issue by do-dop** [ttakkeun/Backend_Spring#105]
## Issue: ✅ Todo
코드리뷰

## ✏️ Description
애플 로그인/회원가입, 토큰 재발급, JWT 토큰, 일지 목록 조회, 일지 사진 업로드, 펫 프로필 사진 저장/수정

## To-Do List
- [x] 애플 로그인/회원가입
- [x] 토큰 재발급
- [x] JWT 토큰
- [x] 일지 목록 조회
- [ ] 일지 사진 업로드
- [ ] 펫 프로필 사진 저장/수정
