### ISSUE TITLE
[Feat] 진단 관련 API 구현

### ISSUE THREAD

**Issue by 0-x-14** [ttakkeun/Backend_Spring#30]
## Issue: ✅ Todo
진단 관련 API 구현

## ✏️ Description
진단 관련 API 구현

## To-Do List
- [x] 사용자 포인트 조회 API #29  
- [ ] 진단 결과 목록 조회 API 
- [ ] AI 진단 API 
- [x] 사용자 포인트 차감 API #31 
- [ ] 네이버 쇼핑 정보 업데이트 API
- [x] 진단서 상세 내용 조회 API
