### ISSUE TITLE
[Feat] 일지 API 구현

### ISSUE THREAD

**Issue by riadan710** [ttakkeun/Backend_Spring#42]
## Issue: ✅ Todo
일지 관련 API 구현

## ✏️ Description
일지 관련 API를 구현합니다 👍 

## To-Do List
- [x] 일지 질문 조회
- [x] 일지 엔티티 수정 (설명 텍스트도 추가)
- [x] 일지 답변 저장
