### ISSUE TITLE
[Refactor] 진단 API 사용자 조회 방식 변경

### ISSUE THREAD

**Issue by 0-x-14** [ttakkeun/Backend_Spring#47]
## Issue: ✅ Todo
진단 API 로그인 방식 변경

## ✏️ Description
memberId 임의로 입력받는 부분 삭제
@AuthenticationPrincipal 추가

## To-Do List
- [x] 진단서 API 로그인 방식 변경
- [x] test 경로 추가
- [x] @Operation 어노테이션 추가
