### ISSUE TITLE
[Feat] @Authenticationprincipal 어노테이션 사용

### ISSUE THREAD

**Issue by riadan710** [ttakkeun/Backend_Spring#89]
## Issue: ✅ Todo
@Authenticationprincipal 어노테이션 사용하여 모든 API 로직 변경

## ✏️ Description
API 로직 변경

## To-Do List
- [x] 반려동물 프로필 API 수정
- [x] 반려동물 프로필 수정 API 구현
- [x] 일지 API 수정
